name: paperwork
base: core22
adopt-info: paperwork
summary: Paperwork is a personal document manager.
description: |
  Paperwork is a personal document manager. It manages scanned documents and PDFs.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

plugs:
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo


slots:
  paperwork:
    interface: dbus
    bus: session
    name: work.openpaper.Paperwork

apps:
  paperowrk:
    command: usr/bin/paperwork
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - avahi-observe
      - avahi-control
      - bluez
      - system-observe
      - cups
      - network
      - network-status
      - network-bind
      - screen-inhibit-control
      - unity7
    common-id: work.openpaper.Paperwork
    #desktop: usr/share/applications/


parts:
  paperwork:
    source: https://gitlab.gnome.org/World/OpenPaperwork/paperwork.git
    source-tag: 2.1.2
    plugin: make
    build-packages:
      - python3-virtualenv 
      - virtualenv 
      - python3-dev 
      - meson 
      - build-essential 
      - libsane-dev 
      - python3-gi 
      - valac 
      - wget
      - curl
      - git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      
